project/messages/views.py
from flask import redirect, render_template, request, url_for, Blueprint, jsonify
from project.messages.models import Message
from project.users.models import User
from project.users.views import ensure_correct_user
from project.messages.forms import MessageForm, LikeForm
from flask_login import current_user, login_required
from project import db

messages_blueprint = Blueprint(
    'messages', __name__, template_folder='templates')


@messages_blueprint.route('/', methods=["POST"])
@login_required
def index(id):
    if current_user.get_id() == str(id):
        form = MessageForm()
        if form.validate():
            new_message = Message(text=form.text.data, user_id=id)
            db.session.add(new_message)
            db.session.commit()
            return redirect(url_for('users.show', id=id))
    return render_template('messages/new.html', form=form)

@messages_blueprint.route('/<int:message_id>/likes', methods=['POST', 'DELETE'])
@login_required
@ensure_correct_user
def ajax_like_add_del(id, message_id):
    user=User.query.get_or_404(id)
    if request.method == 'POST':
        if id == user.id:
            user.message_likes.append(Message.query.get_or_404(message_id))
            db.session.commit()
            return jsonify('you managed to like something')
        return jsonify('like was not registered')
    if request.method == 'DELETE':
        if id == user.id:
            user.message_likes.remove(Message.query.get_or_404(message_id))
            db.session.commit()
            like_count = len(user.message_likes)
            temp = jsonify({'like_count': like_count})
            return jsonify({'like_count': like_count})
        return jsonify('unlike was not registered')

@messages_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(id):
    return render_template('messages/new.html', form=MessageForm())


@messages_blueprint.route('/<int:message_id>', methods=["GET", "DELETE"])
def show(id, message_id):
    found_message = Message.query.get_or_404(message_id)
    form = LikeForm()
    if request.method == b"DELETE" and current_user.id == id:
        db.session.delete(found_message)
        db.session.commit()
        return redirect(url_for('users.show', id=id))
    return render_template('messages/show.html', id=id, message=found_message, form = form)

project/users/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash, session
from project.users.models import User
from project.users.forms import UserForm, UserEditForm, LoginForm
from project import db
from sqlalchemy.exc import IntegrityError
from flask_login import login_user, logout_user, current_user, login_required
from functools import wraps
from project.messages.models import Message

users_blueprint = Blueprint('users', __name__, template_folder='templates')


def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('id') != current_user.id:
            flash({'text': "Not Authorized", 'status': 'danger'})
            return redirect(url_for('root'))
        return fn(*args, **kwargs)

    return wrapper


@users_blueprint.route('/', methods=["GET"])
def index():
    if 'user_id' in session:
        user_logged_in = True
    else:
        user_logged_in = False
    search = request.args.get('q')
    users = None
    if search is None or search == '':
        users = User.query.all()
    else:
        users = User.query.filter(User.username.like("%%%s%%" % search)).all()
    return render_template('users/index.html', users=users, user_logged_in=user_logged_in)


@users_blueprint.route('/signup', methods=["GET", "POST"])
def signup():
    form = UserForm()
    if request.method == "POST":
        if form.validate():
            try:
                new_user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=form.password.data)
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
            except IntegrityError as e:
                flash({'text': "Username already taken", 'status': 'danger'})
                return render_template('users/signup.html', form=form)
            return redirect(url_for('root'))
    return render_template('users/signup.html', form=form)


@users_blueprint.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST":
        if form.validate():
            found_user = User.authenticate(form.username.data,
                                           form.password.data)
            if found_user:
                login_user(found_user)
                session['user_id'] = found_user.id
                flash({
                    'text': f"Hello, {found_user.username}!",
                    'status': 'success'
                })
                return redirect(url_for('root'))
            flash({'text': "Invalid credentials.", 'status': 'danger'})
            return render_template('users/login.html', form=form)
    return render_template('users/login.html', form=form)


@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('user_id', None)
    flash({'text': "You have successfully logged out.", 'status': 'success'})
    return redirect(url_for('users.login'))


@users_blueprint.route('/<int:id>/edit')
@login_required
@ensure_correct_user
def edit(id):
    return render_template(
        'users/edit.html', form=UserEditForm(), user=User.query.get_or_404(id))


@users_blueprint.route('/<int:follower_id>/follower', methods=['POST', 'DELETE'])
@login_required
def follower(follower_id):
    followed = User.query.get_or_404(follower_id)
    if request.method == 'POST':
        current_user.following.append(followed)
    else:
        current_user.following.remove(followed)
    db.session.add(current_user)
    db.session.commit()
    return redirect(url_for('users.following', id=current_user.id))


@users_blueprint.route('/<int:id>/following', methods=['GET'])
@login_required
def following(id):
    return render_template('users/following.html', user=User.query.get(id))


@users_blueprint.route('/<int:id>/followers', methods=['GET'])
@login_required
def followers(id):
    return render_template('users/followers.html', user=User.query.get_or_404(id))

@users_blueprint.route('/<int:id>/likes')
@login_required
def likes(id):
    user=User.query.get_or_404(id)
    ids = [msg.id for msg in User.query.get_or_404(id).message_likes]
    messages = Message.query.filter(Message.id.in_(ids)).order_by('timestamp desc').limit(100)
    return render_template('users/likes.html', user = user, messages = messages)

@users_blueprint.route('/<int:id>', methods=["GET", "PATCH", "DELETE"])
def show(id):
    found_user = User.query.get_or_404(id)
    if (request.method == 'GET' or current_user.is_anonymous or current_user.get_id() != str(id)):
        return render_template('users/show.html', user=found_user)
    if request.method == b"PATCH":
        form = UserEditForm(request.form)
        if form.validate():
            if User.authenticate(found_user.username, form.password.data):
                found_user.username = form.username.data
                found_user.email = form.email.data
                found_user.image_url = form.image_url.data
                found_user.header_image_url = form.header_image_url.data or None
                found_user.bio = form.bio.data
                found_user.full_name = form.full_name.data
                found_user.location = form.location.data
                db.session.add(found_user)
                db.session.commit()
                return redirect(url_for('users.show', id=id))
            flash({
                'text': "Wrong password, please try again.",
                'status': 'danger'
            })
        return render_template('users/edit.html', form=form, user=found_user)
    if request.method == b"DELETE":
        db.session.delete(found_user)
        db.session.commit()
        return redirect(url_for('users.signup'))

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Warbler</title>
  <link
    rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
    integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
    integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
    crossorigin="anonymous"></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
    integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
    crossorigin="anonymous"></script>
  <script src="https://use.fontawesome.com/d2766f5640.js"></script>
  <link
    rel="stylesheet"
    href="{{ url_for('static', filename='stylesheets/style.css') }}">
  <link
    rel="shortcut icon"
    href="{{ url_for('static', filename='favicon.ico') }}">
</head>

{% if request.endpoint == 'users.signup' or request.endpoint == 'users.login' %}
  <body class="onboarding">
{% else %}
  <body>
{% endif %}
  <nav class="navbar navbar-expand">
    <div class="container-fluid">
      <div class="navbar-header">
        <a href="{{ url_for('root') }}" class="navbar-brand">
          <img src="{{ url_for('static', filename='images/warbler-logo.png') }}" alt="">
          <span>Warbler</span>
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-right" action={{ url_for( 'users.index') }} method='GET'>
            <input type="text" name="q" class="form-control" placeholder="Search Warbler" id="search">
            <button type="submit" class="btn btn-default">
              <span class="fa fa-search"></span>
            </button>
          </form>
        </li>
        {% if current_user.is_anonymous %}
        <li>
          <a href="{{ url_for('users.signup') }}">Sign up</a>
        </li>
        <li>
          <a href="{{ url_for('users.login') }}">Log in</a>
        </li>
        {% else %}
        <li>
          <a href="{{ url_for('users.show', id=current_user.id) }}">
            <img src="{{ current_user.image_url }}" alt="{{ current_user.username }}">
          </a>
        </li>
        <li>
          <a href="{{ url_for('messages.new', id=current_user.id) }}">New Message</a>
        </li>
        <li>
          <a href="{{ url_for('users.logout') }}">Log out</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% for message in get_flashed_messages() %}
      <div class="alert alert-{{ message['status'] }}">
        {{ message['text'] }}
      </div>
    {% endfor %}
    {% block content %}
    {% endblock %}
  <script src="{{ url_for('static', filename='javascripts/app.js') }}"></script>
  </div>
</body>
</html>

project/templates/home.html
{% extends 'base.html' %} 
{% block content %} 
{% if current_user.is_authenticated %}
<div class="row">
  <aside class="col-lg-3 col-md-12" id="home-aside">
    <div class="card user-card">
      <div>
        {% if current_user.header_image_url != None %}
            <img src="{{ current_user.header_image_url }}" alt="heading image" class="card-hero">
        {% else %}
            <img src="{{ url_for('static', filename='images/warbler-hero.jpg') }}" alt="" class="card-hero">
        {% endif %}
        <a href="{{ url_for('users.show', id=current_user.id) }}" class="card-link">
          <img src="{{ current_user.image_url }}" alt="Image for {{ current_user.username }}" class="card-image">
          <p>@{{ current_user.username }}</p>
        </a>
        <ul class="user-stats nav nav-pills">
          <li class="stat">
            <p class="small">Messages</p>
            <h4>
              <a href="{{ url_for('users.show', id=current_user.id) }}">{{ current_user.messages.count() }}</a>
            </h4>
          </li>
          <li class="stat">
            <p class="small">Following</p>
            <h4>
              <a href="{{ url_for('users.following', id=current_user.id) }}">{{ current_user.following.count() }}</a>
            </h4>
          </li>
          <li class="stat">
            <p class="small">Followers</p>
            <h4>
              <a href="{{ url_for('users.followers', id=current_user.id) }}">{{ current_user.followers.count() }}</a>
            </h4>
          </li>
        </ul>
      </div>
    </div>
  </aside>
  <div class="col-lg-6 col-md-12">
    <ul class="list-group" id="messages">
      {% for message in messages %}
      <li class="list-group-item">
        <a href="{{ url_for('messages.show', id=message.user.id, message_id=message.id ) }}" class="message-link"/>
        <a href="{{ url_for('users.show', id=message.user.id) }}">
          <img src="{{ message.user.image_url }}" alt="" class="timeline-image">
        </a>
        <div class="message-area">
          <a href="{{ url_for('users.show', id=message.user.id) }}">@{{ message.user.username }}</a>
          <span class="text-muted">{{ message.timestamp.strftime('%d %B %Y') }}</span>
          <p>{{ message.text }}</p>
        </div>
        {% if message.user_id != current_user.id %}
          <div class="like-area ml-auto" id="{{current_user.id}}.{{message.id}}">
              {% if current_user.is_liking(message) %}
                <i class="fa fa-heart" aria-hidden="true"></i>
              {% else %}
                <i class="fa fa-heart-o" aria-hidden="true"></i>
              {% endif %}  
          </div>
        {% endif %}
      
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% else %}
<div class="home-hero">
  <h1>What's Happening?</h1>
  <h4>New to Warbler?</h4>
  <p>Sign up now to get your own personalized timeline!</p>
  <a href="{{ url_for('users.signup') }}" class="btn btn-primary">Sign up</a>
</div>
{% endif %}
{% endblock %}

project/templates/user_page.html
{% extends 'base.html' %}
{% block content %}
{% if user.header_image_url != None %}
    <div id="warbler-hero" style="background-image:url('{{ user.header_image_url }}')" class="full-width"></div>
{% else %}
    <div id="warbler-hero" class="full-width"></div>
{% endif %}
<img src="{{ user.image_url }}" alt="Image for {{ user.username }}" id="profile-avatar">
<div class="row full-width">
  <div class="container">
    <div class="row justify-content-end">
      <div class="col-9">
        <ul class="user-stats nav nav-pills">
          <li class="stat">
            <p class="small">Messages</p>
            <h4>
              <a href="{{ url_for('users.show', id=user.id) }}">{{ user.messages.count() }}</a>
            </h4>
          </li>
          <li class="stat">
            <p class="small">Following</p>
            <h4>
              <a href="{{ url_for('users.following', id=user.id) }}">{{ user.following.count() }}</a>
            </h4>
          </li>
          <li class="stat">
            <p class="small">Followers</p>
            <h4>
              <a href="{{ url_for('users.followers', id=user.id) }}">{{ user.followers.count() }}</a>
            </h4>
          </li>
          <li class="stat">
            <p class="small">Likes</p>
            <h4>
              <a id="like-count" href="{{ url_for('users.likes', id=user.id) }}">{{ user.message_likes|length }}</a>
            </h4>
          </li>
          <div class="ml-auto">
            {% if current_user.id == user.id %}
            <a href="{{ url_for('users.edit', id=user.id) }}" class="btn btn-outline-secondary">Edit Profile</a>
            <form method="POST" action="{{url_for('users.show', id=user.id)}}?_method=DELETE" class="form-inline">
              <input type="submit" value="Delete Profile" class="btn btn-outline-danger ml-2">
            </form>
            {% elif current_user.is_authenticated %} {% if current_user.is_following(user) %}
            <form method="POST" action="{{url_for('users.follower', follower_id=user.id)}}?_method=DELETE">
              <input type="submit" value="Unfollow" class="btn btn-primary">
            </form>
            {% else %}
            <form method="POST" action="{{url_for('users.follower', follower_id=user.id)}}">
              <input type="submit" value="Follow" class="btn btn-outline-primary">
            </form>
            {% endif %} {% endif %}
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <h4 id="sidebar-username">@{{ user.username }}</h4>
    {% if user.full_name %}
      <h6 class="mt-3 mb-1">Name:</h6>
      <h5 class="mt-1" id="sidebar-full_name">{{ user.full_name }}</h5>
    {% endif %}
    {% if user.location %}
      <h6 class="mt-3 mb-1">Location:</h6>
      <h5 class="mt-1" id="sidebar-location">{{ user.location }}</h5>
    {% endif %}
    {% if user.bio %}
      <h6 class="mt-3 mb-1">Bio:</h6>
      <p class="mt-1" id="sidebar-bio">{{ user.bio }}</p>
    {% endif %}
  </div>
  {% block user_details %}
  {% endblock %}
</div>
</div>
{% endblock %}