project/messages/models.py
from project import db
from datetime import datetime
# from project.users.models import User

Likes = db.Table('likes',
        db.Column('id',
                db.Integer,
                primary_key=True),
        db.Column('user_id',
                db.Integer,
                db.ForeignKey('users.id', ondelete="cascade")),
        db.Column('message_id',
                db.Integer,
                db.ForeignKey('messages.id', ondelete="cascade")),
        db.UniqueConstraint('user_id', 'message_id', name="one_time_like")
        )

class Message(db.Model):

    __tablename__ = 'messages'

    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'))
    user_likes = db.relationship('User',
        secondary=Likes,
        backref=db.backref('message_likes'))

    def __init__(self, text, user_id, timestamp=datetime.utcnow()):
        self.text = text
        self.user_id = user_id
        self.timestamp = timestamp

project/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired


class MessageForm(FlaskForm):
    text = StringField('text', validators=[DataRequired()], widget=TextArea())

class LikeForm(FlaskForm):
    pass

project/messages/views.py
from flask import redirect, render_template, request, url_for, Blueprint, jsonify
from project.messages.models import Message
from project.users.models import User
from project.users.views import ensure_correct_user
from project.messages.forms import MessageForm, LikeForm
from flask_login import current_user, login_required
from project import db

messages_blueprint = Blueprint(
    'messages', __name__, template_folder='templates')


@messages_blueprint.route('/', methods=["POST"])
@login_required
def index(id):
    if current_user.get_id() == str(id):
        form = MessageForm()
        if form.validate():
            new_message = Message(text=form.text.data, user_id=id)
            db.session.add(new_message)
            db.session.commit()
            return redirect(url_for('users.show', id=id))
    return render_template('messages/new.html', form=form)

@messages_blueprint.route('/<int:message_id>/likes', methods=['POST', 'DELETE'])
@login_required
@ensure_correct_user
def ajax_like_add_del(id, message_id):
    user=User.query.get_or_404(id)
    if request.method == 'POST':
        if id == user.id:
            user.message_likes.append(Message.query.get_or_404(message_id))
            db.session.commit()
            return jsonify('you managed to like something')
        return jsonify('like was not registered')
    if request.method == 'DELETE':
        if id == user.id:
            user.message_likes.remove(Message.query.get_or_404(message_id))
            db.session.commit()
            like_count = len(user.message_likes)
            temp = jsonify({'like_count': like_count})
            return jsonify({'like_count': like_count})
        return jsonify('unlike was not registered')

@messages_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(id):
    return render_template('messages/new.html', form=MessageForm())


@messages_blueprint.route('/<int:message_id>', methods=["GET", "DELETE"])
def show(id, message_id):
    found_message = Message.query.get_or_404(message_id)
    form = LikeForm()
    if request.method == b"DELETE" and current_user.id == id:
        db.session.delete(found_message)
        db.session.commit()
        return redirect(url_for('users.show', id=id))
    return render_template('messages/show.html', id=id, message=found_message, form = form)

project/messages/templates/messages/new.html
{% extends 'base.html' %} 
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <form action="{{ url_for('messages.index', id=current_user.id) }}" method="POST">
      {{ form.csrf_token }}
      <div>
        {% if form.text.errors %}
          {% for error in form.text.errors %}
          <span class="text-danger">
            {{ error }}
          </span>
          {% endfor %}
        {% endif %}
        {{ form.text(placeholder="What's happening?", class="form-control", rows="3") }}
      </div>
      <button type="submit" class="btn btn-outline-success btn-block">Add my message!</button>
    </form>
  </div>
</div>
{% endblock %}

project/messages/templates/messages/show.html
{% extends 'base.html' %} 
{% block content %}
<div class="bg"></div>
<div class="row justify-content-center">
  <div class="col-md-6">
    <ul class="list-group no-hover" id="messages">
      <li class="list-group-item">
        <a href="{{ url_for('users.show', id=message.user.id) }}">
          <img src="{{ message.user.image_url }}" alt="" class="timeline-image">
        </a>
        <div class="message-area">
          <div class="message-heading">
            <a href="{{ url_for('users.show', id=message.user.id) }}">@{{ message.user.username }}</a>
            
            {% if current_user.is_authenticated %}
              <div class="row ml-auto mr-1">
                
                {% if message.user_id != current_user.id %}
                  <div class="like-area mt-1" id="{{current_user.id}}.{{message.id}}">
                      {% if current_user.is_liking(message) %}
                        <i class="fa fa-heart fa-2x" aria-hidden="true"></i>
                      {% else %}
                        <i class="fa fa-heart-o fa-2x" aria-hidden="true"></i>
                      {% endif %}  
                  </div>
                {% endif %}

              {% if current_user.id == message.user.id %}
                <form class="form-inline mx-1" method="POST" action="{{url_for('messages.show', message_id=message.id, id=message.user.id)}}?_method=DELETE">
                  <input type="submit" value="Delete" class="btn btn-outline-danger btn-sm">
                </form>
              {% elif current_user.is_following(message.user) %}
                <form class="form-inline mx-1" method="POST" action="{{url_for('users.follower', follower_id=message.user.id)}}?_method=DELETE">
                  <input type="submit" value="Unfollow" class="btn btn-primary btn-sm">
                </form>
              {% else %}
                <form class="form-inline mx-1" method="POST" action="{{url_for('users.follower', follower_id=message.user.id)}}">
                  <input type="submit" value="Follow" class="btn btn-outline-primary btn-sm">
                </form>
              {% endif %}
              </div>
            {% endif %}
          </div>
          <p class="single-message">{{ message.text }}</p>
          <span class="text-muted">{{ message.timestamp.strftime('%d %B %Y') }}</span>
        </div>
      </li>
    </ul>
  </div>
</div>
{% endblock %}